[package]
name = "pedump"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
capstone = "0.14.0"
chrono = "0.4.42"
clap = { version = "4.5.54", features = ["derive"] }
regex = "1.12.2"
strum = "0.27.2"
strum_macros = "0.27.2"
